/**
 * tutorPrompt.ts — 6-section cached system prompt builder.
 * Each section returns an Anthropic text block with optional cache_control,
 * so the backend can pass `system: buildSystemPrompt(...)` directly.
 *
 * Sections:
 *   1. PERSONA              — stable, cached
 *   2. CURRICULUM INDEX     — weekly refresh, cached
 *   3. STUDENT PROFILE      — daily refresh, cached
 *   4. MSV (motivation)     — per-session, NOT cached (changes often)
 *   5. TURN CONTEXT         — per-turn, NOT cached
 *   6. TOOLS USAGE          — stable, cached
 *
 * Cache breakpoints are placed after sections 1, 2, 3, 6 (mid+stable prefix).
 */

export interface TutorProfile {
  level: 'beginner' | 'intermediate' | 'advanced'
  masteredHebrew: string[] // hebrew titles
  inProgressHebrew: string[]
  strugglesHebrew: string[]
}

export interface TutorTurnContext {
  routeHe: string | null // "מסך לימוד — חציון"
  topicHe: string | null // "חציון"
  lastQuizQuestion: string | null
  lastQuizUserAnswer: string | null
  lastQuizCorrect: boolean | null
}

export interface TutorMSV {
  flowState: string // e.g. "neutral" | "anxiety" | "boredom"
  confidence: number // 0..1
  primaryDeficit: string // e.g. "capability" | "none"
}

interface CachedBlock {
  type: 'text'
  text: string
  cache_control?: { type: 'ephemeral' }
}

const PERSONA = `את/ה "וופל", המורה הפרטי של WaffleStack לסטטיסטיקה.

הזהות שלך:
- חבר/ה חכמ/ה שיודע/ת את החומר. לא מורה מהזרם הישן.
- מדבר/ת עברית טבעית, ישירה, חמה, אבל לא מתחנפ/ת.
- פונה ישירות לסטודנט/ית (גוף שני).
- כשאת/ה לא בטוח/ה, אומר/ת "אני לא בטוח/ה" — לא ממציא/ה.

השיטה שלך (סוקרטית כברירת מחדל):
1. שאל/י שאלה מנחה לפני שאת/ה עונ/ה.
2. דוגמה לפני נוסחה. תמיד.
3. רעיון אחד לכל הודעה. לא קירות טקסט.
4. סגור/י עם בדיקת הבנה: "הצלחת/הצלחתי לעקוב? בא ננסה דוגמה?"
5. אם הסטודנט/ית מבקש/ת ישירות תשובה ("תן לי תשובה", "אני ממהר/ת") — תן/י תשובה ישירה ואז שאל/י אם להעמיק.

כללי ברזל:
- לעולם אל תמציא/י נוסחה. השתמש/י בכלי get_topic_formulas.
- מתמטיקה ב-LaTeX, לא ASCII. כתוב/י $x^2$ ולא x^2.
- נושאים מחוץ לקורס: הפנה/י בעדינות חזרה לקורס.
- אסור להעיר על אינטליגנציה, ציון מהעבר, או להשוות לתלמידים אחרים.
- אם משהו אישי כבד עולה (פגיעה עצמית, אלימות): הפנה/י בעדינות למבוגר/ת אחראי/ת או למוקד 105.`

const TOOLS_USAGE = `כלים זמינים:
- get_current_lesson_summary() → סיכום של השיעור הפעיל (מבוסס על מסך נוכחי).
- get_topic_formulas(topicId) → רשימת נוסחאות עיקריות של נושא.
- list_completed_topics() → רשימת הנושאים שהסטודנט/ית כבר סיים/ה.
- quiz_hint(questionText) → רמז סוקרטי, לא תשובה.

מתי להפעיל:
- "מה הנוסחה ל..." → get_topic_formulas לפני שאת/ה כותב/ת אותה.
- "מה היה בשיעור" / "אני לא זוכר/ת" → get_current_lesson_summary.
- "תעזרי לי עם השאלה" + יש שאלת קוויז → quiz_hint, אל תיתן/י תשובה ישירה.
- "מה למדתי עד עכשיו" → list_completed_topics.

חשוב: אל תיתן/י תשובה לקוויז ישירות. רק רמזים מנחים.`

// Static stub of the curriculum index — would be generated by buildTutorIndex script.
// Keeping ~10 core topics short enough for the cached prefix.
const CURRICULUM_INDEX = `אינדקס קורס WaffleStack (10 נושאים):
- mean / "ממוצע" — סכום החלקי במספר הערכים. דורש: אין.
- median / "חציון" — הערך האמצעי לאחר מיון. דורש: mean.
- stddev / "סטיית תקן" — שורש השונות; פיזור סביב הממוצע. דורש: mean.
- normal / "התפלגות נורמלית" — עקומת פעמון, כלל 68-95-99.7. דורש: stddev.
- sampling / "מדגם" — בחירת תת-קבוצה מאוכלוסייה; משפט הגבול המרכזי. דורש: normal.
- hypothesis / "מבחני השערות" — H0 מול H1, ערך p, מובהקות. דורש: sampling.
- correlation / "מתאם" — חוזק וכיוון קשר ($-1$ עד $1$). דורש: stddev.
- regression / "רגרסיה" — משוואה $y = a + bx$ לחיזוי. דורש: correlation.
- ci / "רווח סמך" — טווח שבתוכו פרמטר אוכלוסייה בסבירות נתונה. דורש: sampling.
- binomial / "התפלגות בינומית" — מספר ההצלחות ב-n ניסיונות עצמאיים. דורש: mean.`

function buildProfileSection(p: TutorProfile): string {
  const mastered = p.masteredHebrew.length ? p.masteredHebrew.join(', ') : 'עדיין אין'
  const inProgress = p.inProgressHebrew.length ? p.inProgressHebrew.join(', ') : 'אין'
  const struggles = p.strugglesHebrew.length ? p.strugglesHebrew.join(', ') : 'אין דפוס מובהק'
  return `פרופיל סטודנט/ית:
- רמה: ${p.level}
- שולט/ת: ${mastered}
- בתהליך: ${inProgress}
- נקודות חולשה: ${struggles}`
}

function buildMSVSection(msv: TutorMSV): string {
  // Derive tone hint
  let tone = 'peer'
  if (msv.flowState === 'anxiety' || msv.confidence < 0.4) tone = 'restorative'
  else if (msv.flowState === 'boredom' && msv.confidence > 0.7) tone = 'coach'
  return `מצב מוטיבציה: flowState=${msv.flowState}, confidence=${msv.confidence.toFixed(2)}, primaryDeficit=${msv.primaryDeficit}
טון לפעולה: ${tone}`
}

function buildTurnSection(ctx: TutorTurnContext): string {
  const route = ctx.routeHe ?? 'לא ידוע'
  const topic = ctx.topicHe ?? 'אין'
  let quizLine = 'אין שאלת קוויז אחרונה.'
  if (ctx.lastQuizQuestion) {
    const correctness =
      ctx.lastQuizCorrect === null ? '?' : ctx.lastQuizCorrect ? 'נכונה' : 'שגויה'
    quizLine = `שאלת קוויז אחרונה: ${ctx.lastQuizQuestion}
תשובת סטודנט/ית: ${ctx.lastQuizUserAnswer ?? '—'} (${correctness})`
  }
  return `מסך נוכחי: ${route}
נושא פעיל: ${topic}
${quizLine}`
}

export function buildSystemPrompt(
  profile: TutorProfile,
  msv: TutorMSV,
  turn: TutorTurnContext,
): CachedBlock[] {
  return [
    // Section 1 — Persona (cached)
    { type: 'text', text: PERSONA, cache_control: { type: 'ephemeral' } },
    // Section 2 — Curriculum index (cached)
    { type: 'text', text: CURRICULUM_INDEX, cache_control: { type: 'ephemeral' } },
    // Section 6 — Tools usage (cached, placed early in stable prefix)
    { type: 'text', text: TOOLS_USAGE, cache_control: { type: 'ephemeral' } },
    // Section 3 — Student profile (cached, refreshes ~daily)
    { type: 'text', text: buildProfileSection(profile), cache_control: { type: 'ephemeral' } },
    // Section 4 — MSV (not cached, changes per session)
    { type: 'text', text: buildMSVSection(msv) },
    // Section 5 — Turn context (not cached, changes every turn)
    { type: 'text', text: buildTurnSection(turn) },
  ]
}

/** Convenience for the edge function / client — flatten to a plain string if SDK can't be loaded. */
export function flattenSystemPrompt(blocks: CachedBlock[]): string {
  return blocks.map((b) => b.text).join('\n\n')
}

// ── Default stub data ──────────────────────────────────────────────────────────
// The edge function pulls these from the request body when richer signals exist.

export const DEFAULT_PROFILE: TutorProfile = {
  level: 'beginner',
  masteredHebrew: [],
  inProgressHebrew: [],
  strugglesHebrew: [],
}

export const DEFAULT_MSV: TutorMSV = {
  flowState: 'neutral',
  confidence: 0.6,
  primaryDeficit: 'none',
}

export const DEFAULT_TURN: TutorTurnContext = {
  routeHe: null,
  topicHe: null,
  lastQuizQuestion: null,
  lastQuizUserAnswer: null,
  lastQuizCorrect: null,
}
